[2023-03-29 16:49:01,305] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.transform_data_task manual__2023-03-29T16:48:36.515119+00:00 [queued]>
[2023-03-29 16:49:01,362] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.transform_data_task manual__2023-03-29T16:48:36.515119+00:00 [queued]>
[2023-03-29 16:49:01,364] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:49:01,366] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 16:49:01,368] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:49:01,423] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): transform_data_task> on 2023-03-29 16:48:36.515119+00:00
[2023-03-29 16:49:01,434] {standard_task_runner.py:52} INFO - Started process 8291 to run task
[2023-03-29 16:49:01,448] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE', 'transform_data_task', 'manual__2023-03-29T16:48:36.515119+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpeoh6ykky', '--error-file', '/tmp/tmpvexb3jkv']
[2023-03-29 16:49:01,452] {standard_task_runner.py:77} INFO - Job 154: Subtask transform_data_task
[2023-03-29 16:49:01,614] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE.transform_data_task manual__2023-03-29T16:48:36.515119+00:00 [running]> on host ebd786f8513c
[2023-03-29 16:49:01,809] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE
AIRFLOW_CTX_TASK_ID=transform_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:48:36.515119+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:48:36.515119+00:00
[2023-03-29 16:50:37,459] {stock_data_transform.py:133} ERROR - An error occurred during transformation: Table or view not found: stock_data; line 1 pos 14;
'Sort ['date ASC NULLS FIRST], false
+- 'Project [*]
   +- 'UnresolvedRelation [stock_data], [], false

[2023-03-29 16:51:39,194] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 16:51:39,365] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE, task_id=transform_data_task, execution_date=20230329T164836, start_date=20230329T164901, end_date=20230329T165139
[2023-03-29 16:51:39,673] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 16:51:40,109] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
