[2023-03-29 16:43:43,169] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_FINAL.ingest_data_into_bigquery manual__2023-03-29T16:40:41.607407+00:00 [queued]>
[2023-03-29 16:43:43,215] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_FINAL.ingest_data_into_bigquery manual__2023-03-29T16:40:41.607407+00:00 [queued]>
[2023-03-29 16:43:43,217] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:43:43,219] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 16:43:43,220] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:43:43,270] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_data_into_bigquery> on 2023-03-29 16:40:41.607407+00:00
[2023-03-29 16:43:43,282] {standard_task_runner.py:52} INFO - Started process 8022 to run task
[2023-03-29 16:43:43,291] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE_FINAL', 'ingest_data_into_bigquery', 'manual__2023-03-29T16:40:41.607407+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp3a_q3syq', '--error-file', '/tmp/tmp3nsm2_kl']
[2023-03-29 16:43:43,295] {standard_task_runner.py:77} INFO - Job 151: Subtask ingest_data_into_bigquery
[2023-03-29 16:43:43,469] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE_FINAL.ingest_data_into_bigquery manual__2023-03-29T16:40:41.607407+00:00 [running]> on host ebd786f8513c
[2023-03-29 16:43:43,631] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE_FINAL
AIRFLOW_CTX_TASK_ID=ingest_data_into_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:40:41.607407+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:40:41.607407+00:00
[2023-03-29 16:43:44,284] {logging_mixin.py:109} INFO - Error creating dataset: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/dataengineering-378316/datasets?prettyPrint=false: Already Exists: Dataset dataengineering-378316:sp_500_data
[2023-03-29 16:43:44,649] {logging_mixin.py:109} INFO - Table sp_500_data.sp_500_data_table already exists.
[2023-03-29 16:43:49,764] {logging_mixin.py:109} INFO - Loaded 1257 rows into sp_500_data.sp_500_data_table
[2023-03-29 16:43:49,769] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 16:43:49,844] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE_FINAL, task_id=ingest_data_into_bigquery, execution_date=20230329T164041, start_date=20230329T164343, end_date=20230329T164349
[2023-03-29 16:43:50,024] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 16:43:50,365] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
