[2023-03-29 17:42:28,297] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T17:37:55.815145+00:00 [queued]>
[2023-03-29 17:42:28,350] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T17:37:55.815145+00:00 [queued]>
[2023-03-29 17:42:28,355] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 17:42:28,360] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 17:42:28,362] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 17:42:28,490] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_data_into_bigquery> on 2023-03-29 17:37:55.815145+00:00
[2023-03-29 17:42:28,508] {standard_task_runner.py:52} INFO - Started process 2659 to run task
[2023-03-29 17:42:28,534] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE', 'ingest_data_into_bigquery', 'manual__2023-03-29T17:37:55.815145+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpnvz2fclj', '--error-file', '/tmp/tmpo781njn_']
[2023-03-29 17:42:28,538] {standard_task_runner.py:77} INFO - Job 165: Subtask ingest_data_into_bigquery
[2023-03-29 17:42:28,735] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T17:37:55.815145+00:00 [running]> on host eebc01130c53
[2023-03-29 17:42:28,956] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE
AIRFLOW_CTX_TASK_ID=ingest_data_into_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T17:37:55.815145+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T17:37:55.815145+00:00
[2023-03-29 17:42:29,868] {logging_mixin.py:109} INFO - Error creating dataset: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/dataengineering-378316/datasets?prettyPrint=false: Already Exists: Dataset dataengineering-378316:sp_500_data
[2023-03-29 17:42:30,174] {logging_mixin.py:109} INFO - Table sp_500_data.sp_500_data_table already exists.
[2023-03-29 17:42:40,822] {logging_mixin.py:109} INFO - Loaded 1257 rows into sp_500_data.sp_500_data_table
[2023-03-29 17:42:40,824] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 17:42:40,877] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE, task_id=ingest_data_into_bigquery, execution_date=20230329T173755, start_date=20230329T174228, end_date=20230329T174240
[2023-03-29 17:42:40,973] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 17:42:41,049] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
