[2023-03-29 13:45:40,511] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v2.transform_data_task manual__2023-03-29T13:42:24.222819+00:00 [queued]>
[2023-03-29 13:45:40,639] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v2.transform_data_task manual__2023-03-29T13:42:24.222819+00:00 [queued]>
[2023-03-29 13:45:40,641] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 13:45:40,644] {taskinstance.py:1239} INFO - Starting attempt 2 of 4
[2023-03-29 13:45:40,645] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 13:45:40,729] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): transform_data_task> on 2023-03-29 13:42:24.222819+00:00
[2023-03-29 13:45:40,740] {standard_task_runner.py:52} INFO - Started process 15163 to run task
[2023-03-29 13:45:40,758] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE_v2', 'transform_data_task', 'manual__2023-03-29T13:42:24.222819+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpw8usry56', '--error-file', '/tmp/tmpvy0nqzf1']
[2023-03-29 13:45:40,766] {standard_task_runner.py:77} INFO - Job 121: Subtask transform_data_task
[2023-03-29 13:45:40,946] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE_v2.transform_data_task manual__2023-03-29T13:42:24.222819+00:00 [running]> on host 5ebc180c7cc0
[2023-03-29 13:45:41,139] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE_v2
AIRFLOW_CTX_TASK_ID=transform_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T13:42:24.222819+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T13:42:24.222819+00:00
[2023-03-29 13:45:56,616] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-29 13:45:56,629] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 15163. PIDs of all processes in the group: [15165, 15163]
[2023-03-29 13:45:56,632] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 15163
[2023-03-29 13:45:56,636] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-29 13:45:56,813] {process_utils.py:70} INFO - Process psutil.Process(pid=15165, status='terminated', started='13:45:40') (15165) terminated with exit code None
[2023-03-29 13:45:56,816] {process_utils.py:70} INFO - Process psutil.Process(pid=15163, status='terminated', exitcode=0, started='13:45:40') (15163) terminated with exit code 0
