[2023-03-29 17:50:56,974] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T17:46:15.004666+00:00 [queued]>
[2023-03-29 17:50:57,030] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T17:46:15.004666+00:00 [queued]>
[2023-03-29 17:50:57,033] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 17:50:57,035] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 17:50:57,037] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 17:50:57,094] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_data_into_bigquery> on 2023-03-29 17:46:15.004666+00:00
[2023-03-29 17:50:57,110] {standard_task_runner.py:52} INFO - Started process 3420 to run task
[2023-03-29 17:50:57,121] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE', 'ingest_data_into_bigquery', 'manual__2023-03-29T17:46:15.004666+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpf2j5bh6i', '--error-file', '/tmp/tmp5kbmxp69']
[2023-03-29 17:50:57,129] {standard_task_runner.py:77} INFO - Job 169: Subtask ingest_data_into_bigquery
[2023-03-29 17:50:57,319] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T17:46:15.004666+00:00 [running]> on host eebc01130c53
[2023-03-29 17:50:57,525] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE
AIRFLOW_CTX_TASK_ID=ingest_data_into_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T17:46:15.004666+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T17:46:15.004666+00:00
[2023-03-29 17:50:58,194] {logging_mixin.py:109} INFO - Error creating dataset: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/dataengineering-378316/datasets?prettyPrint=false: Already Exists: Dataset dataengineering-378316:sp_500_data
[2023-03-29 17:50:58,471] {logging_mixin.py:109} INFO - Table sp_500_data.sp_500_data_table already exists.
[2023-03-29 17:51:04,952] {logging_mixin.py:109} INFO - Loaded 1257 rows into sp_500_data.sp_500_data_table
[2023-03-29 17:51:04,954] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 17:51:05,020] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE, task_id=ingest_data_into_bigquery, execution_date=20230329T174615, start_date=20230329T175056, end_date=20230329T175105
[2023-03-29 17:51:05,117] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 17:51:05,211] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
