[2023-03-29 16:51:45,473] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T16:48:36.515119+00:00 [queued]>
[2023-03-29 16:51:45,518] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T16:48:36.515119+00:00 [queued]>
[2023-03-29 16:51:45,520] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:51:45,521] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 16:51:45,523] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 16:51:45,564] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_data_into_bigquery> on 2023-03-29 16:48:36.515119+00:00
[2023-03-29 16:51:45,575] {standard_task_runner.py:52} INFO - Started process 8624 to run task
[2023-03-29 16:51:45,584] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE', 'ingest_data_into_bigquery', 'manual__2023-03-29T16:48:36.515119+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpg72o7pr8', '--error-file', '/tmp/tmp8t9jk2dc']
[2023-03-29 16:51:45,587] {standard_task_runner.py:77} INFO - Job 155: Subtask ingest_data_into_bigquery
[2023-03-29 16:51:45,718] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE.ingest_data_into_bigquery manual__2023-03-29T16:48:36.515119+00:00 [running]> on host ebd786f8513c
[2023-03-29 16:51:45,874] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE
AIRFLOW_CTX_TASK_ID=ingest_data_into_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:48:36.515119+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T16:48:36.515119+00:00
[2023-03-29 16:51:46,507] {logging_mixin.py:109} INFO - Error creating dataset: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/dataengineering-378316/datasets?prettyPrint=false: Already Exists: Dataset dataengineering-378316:sp_500_data
[2023-03-29 16:51:46,794] {logging_mixin.py:109} INFO - Table sp_500_data.sp_500_data_table already exists.
[2023-03-29 16:51:49,839] {logging_mixin.py:109} INFO - Loaded 1257 rows into sp_500_data.sp_500_data_table
[2023-03-29 16:51:49,841] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 16:51:49,898] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE, task_id=ingest_data_into_bigquery, execution_date=20230329T164836, start_date=20230329T165145, end_date=20230329T165149
[2023-03-29 16:51:49,977] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 16:51:50,169] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
