[2023-03-29 03:54:49,038] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v2.transform_data_task manual__2023-03-29T03:54:37.493629+00:00 [queued]>
[2023-03-29 03:54:49,094] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v2.transform_data_task manual__2023-03-29T03:54:37.493629+00:00 [queued]>
[2023-03-29 03:54:49,097] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 03:54:49,098] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 03:54:49,099] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 03:54:49,189] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): transform_data_task> on 2023-03-29 03:54:37.493629+00:00
[2023-03-29 03:54:49,211] {standard_task_runner.py:52} INFO - Started process 1792 to run task
[2023-03-29 03:54:49,261] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE_v2', 'transform_data_task', 'manual__2023-03-29T03:54:37.493629+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmgaxjlnz', '--error-file', '/tmp/tmpchl7459t']
[2023-03-29 03:54:49,277] {standard_task_runner.py:77} INFO - Job 73: Subtask transform_data_task
[2023-03-29 03:54:49,453] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE_v2.transform_data_task manual__2023-03-29T03:54:37.493629+00:00 [running]> on host 5ebc180c7cc0
[2023-03-29 03:54:49,712] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE_v2
AIRFLOW_CTX_TASK_ID=transform_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T03:54:37.493629+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T03:54:37.493629+00:00
[2023-03-29 03:55:26,271] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-29 03:55:26,286] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 1792. PIDs of all processes in the group: [1797, 1792]
[2023-03-29 03:55:26,289] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 1792
[2023-03-29 03:55:26,295] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-29 03:55:26,711] {process_utils.py:70} INFO - Process psutil.Process(pid=1792, status='terminated', exitcode=0, started='03:54:49') (1792) terminated with exit code 0
[2023-03-29 03:55:27,132] {process_utils.py:70} INFO - Process psutil.Process(pid=1797, status='terminated', started='03:54:49') (1797) terminated with exit code None
